name: app_lecocon_ssbe
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_auth: ^5.3.1
  injectable: ^2.5.0
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  go_router: ^14.3.0
  firebase_core: ^3.6.0
  file_picker: ^8.1.2
  firebase_storage: ^12.3.3
  get_it: ^8.0.0
  path_provider: ^2.1.5
  pdf_thumbnail: ^0.1.6+1
  pdfx: ^2.8.0
  flutter_pdfview: ^1.3.4
  firebase_app_check: ^0.3.1+4




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Amable
      fonts:
        - asset: 'assets/fonts/Amable.ttf'
    - family: Autography
      fonts:
        - asset: 'assets/fonts/Autography.otf'

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon/logo.png"
  remove_alpha_ios: true